version: '3'

networks:
  dev:

services:
  db:
    image: postgres:13
    container_name: psql
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_PORT_LOCAL}:${PG_PORT}"
    networks:
      - dev

  backend:
    image: node:18-alpine  # Используем готовый образ Node.js
    container_name: tgbot
    ports:
      - "${BACKEND_PORT_LOCAL}:${BACKEND_PORT}"
    depends_on:
      - db
    networks:
      - dev
    environment:
      PG_HOST: db
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - .:/app  # Монтируем рабочую директорию
    working_dir: /app  # Устанавливаем рабочую директорию
    command: /bin/sh -c "npm install && npm start"  # Выполняем установку зависимостей и запуск приложения

volumes:
  pgdata:
